### ISSUE TITLE
When out of memory error, URL bar loses URL and history

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#139]
We need to never clear out the URL bar, or lose the history.

- out of memory should leave the URL in bar, leave history, just not reload page automatically
- would be nice if the history was saved so it is there when you restart the app, along with current URL

**Comment by robomex** [comment]
Restoring history of a WKWebView is much trickier than I expected.  There are many SO threads and posts elsewhere about people running into the issue and generally either giving up or _really_ hacking their way around it.  [Here](https://github.com/mozilla-mobile/webxr-ios/issues/123) is a relevant post from Stefan on the Firefox for iOS team creating what looks to be an involved hack around the WKWebView shortcoming.

I had a questionable hack partially developed to save & restore the history, but it was quickly getting uglier and more untenable.  I suggest closing this issue now since losing the URL portion has been fixed and "history" is mentioned generally in https://github.com/mozilla-mobile/webxr-ios/issues/123 and revisiting that issue when there's more time to dedicate to those enhancements (as opposed to the quick-fixes desired when starting on this issue).

**Comment by blairmacintyre** [comment]
This sounds fine;  I think I assumed _we_ were managing the history, I didn't realize we were using the integrated history mechanism.  If the URL isn't cleared, that's more than enough for now!
