### ISSUE TITLE
Make tracking status messages much less invasive

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#147]
We should consider moving the "tracking status box" from being at the upper left, and making it both less "in your face" and a bit more legible.

All corners of display are likely to have "UI" in them, and much of the time, the tracking status is not really important.

Perhaps consider doing it two ways:

- when URL bar is hidden, put an small little icon in the upper right corner, perhaps color coded orange and red (red for things that cause "no tracking").  This is akin to the way an online game might show a "broken network" icon when connectivity is slow, a little icon that comes and goes and tells you there might be something amis.
- when URL bar is shown, get rid of the icon (it would be behind URL bar) and put this text back, but make it less transparent, more legible.

**Comment by robomex** [comment]
With recent changes to the messagePanel, it's possible for the messagePanel to disappear completely.  This happens since, at least right now, the 'relocalizing' message can display indefinitely, so the issue of a disappearing messagePanel should be resolved once this issue is handled: https://github.com/mozilla-mobile/webxr-ios/issues/158
