### ISSUE TITLE
Update to work with latest spec?

### ISSUE THREAD

**Issue by stalgiag** [mozilla-mobile/webxr-ios#183]
Hi! Are there any plans to update this to work with the final WebXR spec API (the version implemented in Chrome 79>)?

This would mean that one could use this XRViewer to view [the official WebXR samples.](https://immersive-web.github.io/webxr-samples/) This level of support would make it much easier to develop cross-platform WebXR projects.

Let me know if I can be helpful in any way, or if there are current plans under development in a different repo. Thanks!

**Comment by blairmacintyre** [comment]
Hi @stalgiag, we are working on a replacement.  We haven't quite shipped it.  It will be based on the Firefox for iOS app, instead of this app.  The javascript API is in the develop branch of https://github.com/MozillaReality/webxr-ios-js

That branch currently implements the base webxr api with a variety of extensions that are non-standard.  As additional webxr features are standardized, we will conform to them.

Google is shipping a range of not-yet-standardized features in Chrome, beyond the basic spec, we will likely be waiting until those features are closer to standardization before reworking the API.

**Comment by stalgiag** [comment]
Amazing thanks for the info and quick response @blairmacintyre. I will check out the linked repo.

I will close this to avoid crowding the issues here. Thanks again!
