### ISSUE TITLE
Link to version 2?

### ISSUE THREAD

**Issue by stalgiag** [mozilla-mobile/webxr-ios#185]
Hi -- is version 2 of this app on Github anywhere? I looked around briefly to no avail. I want to troubleshoot differences in behavior between [my library ](https://github.com/stalgiag/p5.xr) in Android and iOS (courtesy of this app) but I can't read console messages without building version 2 of the app from source.

Any help would be greatly appreciated!

**Comment by robomex** [comment]
There may be a better/more current answer, but in the meantime: https://github.com/mozilla-mobile/firefox-ios/tree/webxr

**Comment by blairmacintyre** [comment]
Thanks Tony.  That is indeed where it is, the "webxr" branch of firefox for ios.

Note:  the branch is a bit of a pain to build right now, not least of which because the latest XCode it will build with is 11.3.1 (due to some dependencies).  I'd like to merge in the latest FF for iOS master branch and update, but that's going to be some work I think, as a lot has changed since the late December version we based the webxr branch on.

**Comment by stalgiag** [comment]
Amazing thank you @blairmacintyre and @robomex ! I will try my luck downgrading my xcode and building.
