### ISSUE TITLE
Occasionally can't put people down on the ground

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla-mobile/webxr-ios#21]
Sometimes, when I load the people page, I will be unable to click and place people. I can reload and then it might work, but seems to be about 50/50? It might be correlated with when I see the "WARNING" text at the bottom.

**Comment by blairmacintyre** [comment]
Any time a page is loaded, ARKit is restarted (by design), and it takes a while for ARKit to initialize (that's the "WARNING" at the bottom).  This error should be more descriptive, the "warning" resource image needs to be changed to something like "ARKit not initialized".

Even after initializing (so we have motion tracking), when that WARNING goes away, picking does nothing until a plane is detected.  The web app example needs to indicated when it does not get a hit on a tap.

**Comment by blairmacintyre** [comment]
This is partially due to bad feedback on the warning icon on screen (https://github.com/mozilla-mobile/webxr-ios/issues/26) and partly due to simplistic coding of the demo.  Need to fix the demo code over in the polyfill (https://github.com/mozilla/webxr-polyfill/issues/35)
