### ISSUE TITLE
No GoogleCardboard (VR) support

### ISSUE THREAD

**Issue by PixelPartner** [mozilla-mobile/webxr-ios#55]
Please mention in the ReadMe that for now only AR mode is working. And maybe a timeline when VR is planned to follow.

**Comment by blairmacintyre** [comment]
Do you mean HMD-based VR on iOS?  I am unsure if that will ever happen in the app itself.

The webxr-polyfill could integrate the cardboard support (used to do webvr on normal browsers) but doing native VR (for cardboard) doesn't buy us anything because we don't get any of the timewarp abilities that are needed to make HMD's non-nausia inducing.

Are you looking to use ARKit with Cardboard?  If so, perhaps add a request to the polyfill (github.com/mozilla/webxr-polyfill) to add this.

**Comment by PixelPartner** [comment]
Understood. But this still should be mentioned in the README, as it states support for "AR and VR" in its title.

**Comment by blairmacintyre** [comment]
@PixelPartner thanks, that is indeed an oversight. Fixed.

**Comment by caffeinum** [comment]
I am thinking about building a virtual desktop with a browser in HMD, based on this code. It will look similar to this, but instead of VNC connection to your computer, it will run just a Web browser.

Also, I am thinking about implementing WebVR binding from the 3D-scene to the Cardboard viewer, so if I browse to the site that supports WebVR scene, it will render it not in the window, but in the space around user.

<img src="https://im3.ezgif.com/tmp/ezgif-3-022ddb2bf8a7.gif">
