### ISSUE TITLE
What is needed for a GeoLocation template WebApp ?

### ISSUE THREAD

**Issue by PixelPartner** [mozilla-mobile/webxr-ios#81]
I imagine to only use ARkit/ARCore to let the user select the ground plane and then let activated location services and compass take over to orient the scene.

**Comment by blairmacintyre** [comment]
So, in WebXR Viewer (released version) we ALWAYS ask ARKit to orient the frame of reference it creates with geospatial coordinates.    So, XYZ should be aligned with EUS.   In the current "develop" version, we're making that optional (since I suspect it uses more power).

That said, in argon.js we did the alignment of location.  It's really easy, and I'd love to have a little library that does this.  Here's how I'd do it if I had the time:
- create a minimal geospatial math library from cesium.js (essentially, their core and data directories).  You can get started by just using the full cesium.js and ignoring the rendering libraries.
- use the geolocation API to get location.  When it updates, save the location along with the accuracy.
- convert the locations you get to FIXED coordianates (which is meters relative to the center of the earth)
- cesium has a method to create a local coordinate system at tangent plane to the earth based on a location in FIXED.  Do this
- now, we don't know what the ACTUAL coordnate system of the origin of ARKit is (i.e., where it's located) and so it will be a slightly different local coordinate system than this, but assume we're close to the origin (i.e., with dozens or hundreds of meters) they will be roughly aligned (the earth's curve is pretty slight).  So, you can assume they are aligned
- use the negative of the camera position (in ARKit coordinates) as the location relative to the local geo coordinate frame you just computed, and convert that back to FIXED.  

At this point, you have a reasonable approximation to the location in geospatial coordinates of the origin of the ARKit coordinates.

And that means you can covert any geospatial location to ARKit coordinates:  convert LLA (the typical inputs) to FIXED, and then transform to local ARKit coordinates (matrix multiply)

Now, the fun part.  There are two problems: reasonable altitudes, and dealing with geolocation updates .  

Over time, you will get new reports from the geolocation API, and each of these will actually compute a DIFFERENT origin for ARKit if you do the above, since the error of the geolocation API is so big.  Updating the origin each frame will cause all geospatial content to jump around.

The first, simple hack, we did in argon.js was to only updated when the reported accuracy from the geolocation api is better than the accuracy of the previous report used to align the origins. This means that on startup, things will update a few times as the location API gets better estimates, but will settle out and only update occasionally.  The downside is that the first report of a given accuracy might not be the best, and you won't pick up new ones:  you can imagine more sophisticated approaches that continually compare the reports to the one being used and uses some new reports, but it's not clear how to do this and actually get better accuracy.

Dealing with altitude also requires some hacking.  The altitude you get from the geolocation API and gps in general is poor quality (worse than Lon/Lat).  cesium has methods for downloading elevation maps and using them to give an altitude estimate for a location.  This turns out to be important, because much of the geospatial data on the internet is just LL, with no A!

I would be very happy to help (provide guidance, pointers to where we did things in argon, etc) someone build out a little library to support geospatial in this way.

**Comment by PixelPartner** [comment]
I'll discuss with my team if we could jump in.

**Comment by robomex** [comment]
Closing as this question appears to have been answered.

**Comment by blairmacintyre** [comment]
Still isn't entirely resolved.   We're working on adding geolocation support, perhaps via a polyfill

**Comment by blairmacintyre** [comment]
added a geolocation app to the new set of examples.  Will likely move the geospatial stuff out of the new webxr polyfill, but it's inside for now.
